import { prisma } from '../config/database';

export interface OrderDocumentSettings {
  autoGenerateInvoiceOnOrder: boolean;
  autoGenerateCourierReceiptOnShipment: boolean;
  defaultCourier: string;
  receiptFooter: string;
  showPricesOnCourierReceipt: boolean;
}

export const DEFAULT_ORDER_DOCUMENT_SETTINGS: OrderDocumentSettings = {
  autoGenerateInvoiceOnOrder: true,
  autoGenerateCourierReceiptOnShipment: true,
  defaultCourier: 'Aramex',
  receiptFooter: 'Generated by WattsStore. Use this document for warehouse handover and courier dispatch.',
  showPricesOnCourierReceipt: false,
};

export async function getOrderDocumentSettings(): Promise<OrderDocumentSettings> {
  const row = await prisma.setting.findUnique({ where: { key: 'orderDocuments' } }).catch(() => null);
  return { ...DEFAULT_ORDER_DOCUMENT_SETTINGS, ...((row?.value as Partial<OrderDocumentSettings> | null) ?? {}) };
}
