export const targetCountries = [
  ['AE', 'United Arab Emirates', 'AED', 'AED', 'ae', 'en-AE', 5],
  ['SA', 'Saudi Arabia', 'SAR', 'SAR', 'sa', 'ar-SA', 15],
  ['QA', 'Qatar', 'QAR', 'QAR', 'qa', 'en-QA', 0],
  ['KW', 'Kuwait', 'KWD', 'KWD', 'kw', 'en-KW', 0],
  ['BH', 'Bahrain', 'BHD', 'BHD', 'bh', 'en-BH', 10],
  ['OM', 'Oman', 'OMR', 'OMR', 'om', 'en-OM', 5],
  ['DZ', 'Algeria', 'DZD', 'DZD', 'dz', 'fr-DZ', 19],
  ['AO', 'Angola', 'AOA', 'AOA', 'ao', 'pt-AO', 14],
  ['BJ', 'Benin', 'XOF', 'CFA', 'bj', 'fr-BJ', 18],
  ['BW', 'Botswana', 'BWP', 'BWP', 'bw', 'en-BW', 14],
  ['BF', 'Burkina Faso', 'XOF', 'CFA', 'bf', 'fr-BF', 18],
  ['BI', 'Burundi', 'BIF', 'BIF', 'bi', 'fr-BI', 18],
  ['CM', 'Cameroon', 'XAF', 'CFA', 'cm', 'fr-CM', 19.25],
  ['CV', 'Cape Verde', 'CVE', 'CVE', 'cv', 'pt-CV', 15],
  ['CF', 'Central African Republic', 'XAF', 'CFA', 'cf', 'fr-CF', 19],
  ['TD', 'Chad', 'XAF', 'CFA', 'td', 'fr-TD', 18],
  ['KM', 'Comoros', 'KMF', 'KMF', 'km', 'fr-KM', 10],
  ['CG', 'Republic of the Congo', 'XAF', 'CFA', 'cg', 'fr-CG', 18],
  ['CD', 'Democratic Republic of the Congo', 'CDF', 'CDF', 'cd', 'fr-CD', 16],
  ['CI', "Cote d'Ivoire", 'XOF', 'CFA', 'ci', 'fr-CI', 18],
  ['DJ', 'Djibouti', 'DJF', 'DJF', 'dj', 'fr-DJ', 10],
  ['EG', 'Egypt', 'EGP', 'EGP', 'eg', 'ar-EG', 14],
  ['GQ', 'Equatorial Guinea', 'XAF', 'CFA', 'gq', 'es-GQ', 15],
  ['ER', 'Eritrea', 'ERN', 'ERN', 'er', 'en-ER', 5],
  ['SZ', 'Eswatini', 'SZL', 'SZL', 'sz', 'en-SZ', 15],
  ['ET', 'Ethiopia', 'ETB', 'ETB', 'et', 'en-ET', 15],
  ['GA', 'Gabon', 'XAF', 'CFA', 'ga', 'fr-GA', 18],
  ['GM', 'Gambia', 'GMD', 'GMD', 'gm', 'en-GM', 15],
  ['GH', 'Ghana', 'GHS', 'GHS', 'gh', 'en-GH', 15],
  ['GN', 'Guinea', 'GNF', 'GNF', 'gn', 'fr-GN', 18],
  ['GW', 'Guinea-Bissau', 'XOF', 'CFA', 'gw', 'pt-GW', 19],
  ['KE', 'Kenya', 'KES', 'KSh', 'ke', 'en-KE', 16],
  ['LS', 'Lesotho', 'LSL', 'LSL', 'ls', 'en-LS', 15],
  ['LR', 'Liberia', 'LRD', 'LRD', 'lr', 'en-LR', 10],
  ['LY', 'Libya', 'LYD', 'LYD', 'ly', 'ar-LY', 0],
  ['MG', 'Madagascar', 'MGA', 'MGA', 'mg', 'fr-MG', 20],
  ['MW', 'Malawi', 'MWK', 'MWK', 'mw', 'en-MW', 16.5],
  ['ML', 'Mali', 'XOF', 'CFA', 'ml', 'fr-ML', 18],
  ['MR', 'Mauritania', 'MRU', 'MRU', 'mr', 'ar-MR', 16],
  ['MU', 'Mauritius', 'MUR', 'MUR', 'mu', 'en-MU', 15],
  ['MA', 'Morocco', 'MAD', 'MAD', 'ma', 'fr-MA', 20],
  ['MZ', 'Mozambique', 'MZN', 'MZN', 'mz', 'pt-MZ', 16],
  ['NA', 'Namibia', 'NAD', 'NAD', 'na', 'en-NA', 15],
  ['NE', 'Niger', 'XOF', 'CFA', 'ne', 'fr-NE', 19],
  ['NG', 'Nigeria', 'NGN', 'NGN', 'ng', 'en-NG', 7.5],
  ['RW', 'Rwanda', 'RWF', 'RWF', 'rw', 'en-RW', 18],
  ['ST', 'Sao Tome and Principe', 'STN', 'STN', 'st', 'pt-ST', 15],
  ['SN', 'Senegal', 'XOF', 'CFA', 'sn', 'fr-SN', 18],
  ['SC', 'Seychelles', 'SCR', 'SCR', 'sc', 'en-SC', 15],
  ['SL', 'Sierra Leone', 'SLE', 'SLE', 'sl', 'en-SL', 15],
  ['SO', 'Somalia', 'SOS', 'SOS', 'so', 'en-SO', 10],
  ['ZA', 'South Africa', 'ZAR', 'R', 'za', 'en-ZA', 15],
  ['SS', 'South Sudan', 'SSP', 'SSP', 'ss', 'en-SS', 18],
  ['SD', 'Sudan', 'SDG', 'SDG', 'sd', 'ar-SD', 17],
  ['TZ', 'Tanzania', 'TZS', 'TZS', 'tz', 'en-TZ', 18],
  ['TG', 'Togo', 'XOF', 'CFA', 'tg', 'fr-TG', 18],
  ['TN', 'Tunisia', 'TND', 'TND', 'tn', 'fr-TN', 19],
  ['UG', 'Uganda', 'UGX', 'UGX', 'ug', 'en-UG', 18],
  ['ZM', 'Zambia', 'ZMW', 'ZMW', 'zm', 'en-ZM', 16],
  ['ZW', 'Zimbabwe', 'USD', '$', 'zw', 'en-ZW', 15],
  ['AL', 'Albania', 'ALL', 'ALL', 'al', 'sq-AL', 20],
  ['AD', 'Andorra', 'EUR', '€', 'ad', 'ca-AD', 4.5],
  ['AT', 'Austria', 'EUR', '€', 'at', 'de-AT', 20],
  ['BY', 'Belarus', 'BYN', 'BYN', 'by', 'ru-BY', 20],
  ['BE', 'Belgium', 'EUR', '€', 'be', 'fr-BE', 21],
  ['BA', 'Bosnia and Herzegovina', 'BAM', 'BAM', 'ba', 'bs-BA', 17],
  ['BG', 'Bulgaria', 'BGN', 'BGN', 'bg', 'bg-BG', 20],
  ['HR', 'Croatia', 'EUR', '€', 'hr', 'hr-HR', 25],
  ['CY', 'Cyprus', 'EUR', '€', 'cy', 'en-CY', 19],
  ['CZ', 'Czechia', 'CZK', 'CZK', 'cz', 'cs-CZ', 21],
  ['DK', 'Denmark', 'DKK', 'DKK', 'dk', 'da-DK', 25],
  ['EE', 'Estonia', 'EUR', '€', 'ee', 'et-EE', 22],
  ['FI', 'Finland', 'EUR', '€', 'fi', 'fi-FI', 25.5],
  ['FR', 'France', 'EUR', '€', 'fr', 'fr-FR', 20],
  ['DE', 'Germany', 'EUR', '€', 'de', 'de-DE', 19],
  ['GR', 'Greece', 'EUR', '€', 'gr', 'el-GR', 24],
  ['HU', 'Hungary', 'HUF', 'HUF', 'hu', 'hu-HU', 27],
  ['IS', 'Iceland', 'ISK', 'ISK', 'is', 'is-IS', 24],
  ['IE', 'Ireland', 'EUR', '€', 'ie', 'en-IE', 23],
  ['IT', 'Italy', 'EUR', '€', 'it', 'it-IT', 22],
  ['LV', 'Latvia', 'EUR', '€', 'lv', 'lv-LV', 21],
  ['LI', 'Liechtenstein', 'CHF', 'CHF', 'li', 'de-LI', 8.1],
  ['LT', 'Lithuania', 'EUR', '€', 'lt', 'lt-LT', 21],
  ['LU', 'Luxembourg', 'EUR', '€', 'lu', 'fr-LU', 17],
  ['MT', 'Malta', 'EUR', '€', 'mt', 'en-MT', 18],
  ['MD', 'Moldova', 'MDL', 'MDL', 'md', 'ro-MD', 20],
  ['MC', 'Monaco', 'EUR', '€', 'mc', 'fr-MC', 20],
  ['ME', 'Montenegro', 'EUR', '€', 'me', 'sr-ME', 21],
  ['NL', 'Netherlands', 'EUR', '€', 'nl', 'nl-NL', 21],
  ['MK', 'North Macedonia', 'MKD', 'MKD', 'mk', 'mk-MK', 18],
  ['NO', 'Norway', 'NOK', 'NOK', 'no', 'nb-NO', 25],
  ['PL', 'Poland', 'PLN', 'PLN', 'pl', 'pl-PL', 23],
  ['PT', 'Portugal', 'EUR', '€', 'pt', 'pt-PT', 23],
  ['RO', 'Romania', 'RON', 'RON', 'ro', 'ro-RO', 19],
  ['RU', 'Russia', 'RUB', 'RUB', 'ru', 'ru-RU', 20],
  ['SM', 'San Marino', 'EUR', '€', 'sm', 'it-SM', 0],
  ['RS', 'Serbia', 'RSD', 'RSD', 'rs', 'sr-RS', 20],
  ['SK', 'Slovakia', 'EUR', '€', 'sk', 'sk-SK', 20],
  ['SI', 'Slovenia', 'EUR', '€', 'si', 'sl-SI', 22],
  ['ES', 'Spain', 'EUR', '€', 'es', 'es-ES', 21],
  ['SE', 'Sweden', 'SEK', 'SEK', 'se', 'sv-SE', 25],
  ['CH', 'Switzerland', 'CHF', 'CHF', 'ch', 'de-CH', 8.1],
  ['TR', 'Turkey', 'TRY', 'TRY', 'tr', 'tr-TR', 20],
  ['UA', 'Ukraine', 'UAH', 'UAH', 'ua', 'uk-UA', 20],
  ['GB', 'United Kingdom', 'GBP', '£', 'gb', 'en-GB', 20],
  ['AM', 'Armenia', 'AMD', 'AMD', 'am', 'hy-AM', 20],
  ['AZ', 'Azerbaijan', 'AZN', 'AZN', 'az', 'az-AZ', 18],
  ['GE', 'Georgia', 'GEL', 'GEL', 'ge', 'ka-GE', 18],
  ['KZ', 'Kazakhstan', 'KZT', 'KZT', 'kz', 'ru-KZ', 12],
  ['KG', 'Kyrgyzstan', 'KGS', 'KGS', 'kg', 'ru-KG', 12],
  ['TJ', 'Tajikistan', 'TJS', 'TJS', 'tj', 'tg-TJ', 15],
  ['TM', 'Turkmenistan', 'TMT', 'TMT', 'tm', 'tk-TM', 15],
  ['UZ', 'Uzbekistan', 'UZS', 'UZS', 'uz', 'uz-UZ', 12],
  ['US', 'Global', 'USD', '$', 'global', 'en-US', 0],
] as const;

export type TargetCountryTuple = typeof targetCountries[number];
