'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { SiteSettings } from '@/lib/cms';

interface CurrencyDisplayForm {
  enabled: boolean;
  baseCurrency: string;
  marginPct: number;
  showBothCurrencies: boolean;
}

interface AdminSettings extends SiteSettings {
  currencyDisplay: CurrencyDisplayForm;
  quoteAutomation: {
    enabled: boolean;
    autoSend: boolean;
    maxAutoValue: number;
    validityDays: number;
    discountTiers: { minQuantity: number; discountPercent: number }[];
  };
  orderDocuments: {
    autoGenerateInvoiceOnOrder: boolean;
    autoGenerateCourierReceiptOnShipment: boolean;
    defaultCourier: string;
    receiptFooter: string;
    showPricesOnCourierReceipt: boolean;
  };
  offerPopup: {
    enabled: boolean;
    title: string;
    body: string;
    ctaLabel: string;
    ctaUrl: string;
    frequencyHours: number;
  };
  taxSettings: {
    countryRates: { countryCode: string; taxClass: string; taxRate: number; taxLabel: string; isInclusive: boolean }[];
  };
  shippingRates: {
    countryRates: { countryCode: string; flatRate?: number; freeOver?: number; baseRate?: number; perKgRate?: number; estimatedDays?: string }[];
  };
  localization: {
    autoDetectCountry: boolean;
    defaultRegion: string;
    supportedLanguages: { code: string; label: string }[];
  };
}

const defaults: AdminSettings = {
  announcementBar: { enabled: true, items: ['Live Regional Product Catalog', 'Request Formal B2B Pricing'] },
  contact: { phone: '+971 50 000 0000', whatsapp: '971500000000', email: 'hello@wattsstore.com', salesEmail: 'sales@wattsstore.com', headquarters: 'Dubai Free Zone, UAE' },
  trustBadges: [{ label: 'Regional Catalog' }, { label: 'Product Documents' }, { label: 'B2B Quotes' }],
  footer: { description: 'Industrial electrical, lighting and solar equipment.', social: {}, certifications: [] },
  offerPopup: {
    enabled: false,
    title: 'Need project pricing?',
    body: 'Send your cart to RFQ and our sales team will prepare a formal quotation.',
    ctaLabel: 'Request Quote',
    ctaUrl: '/ae/quote-basket',
    frequencyHours: 24,
  },
  quoteAutomation: {
    enabled: true,
    autoSend: true,
    maxAutoValue: 50000,
    validityDays: 30,
    discountTiers: [
      { minQuantity: 100, discountPercent: 10 },
      { minQuantity: 25, discountPercent: 5 },
      { minQuantity: 10, discountPercent: 2 },
    ],
  },
  orderDocuments: {
    autoGenerateInvoiceOnOrder: true,
    autoGenerateCourierReceiptOnShipment: true,
    defaultCourier: 'Aramex',
    receiptFooter: 'Generated by WattsStore. Use this document for warehouse handover and courier dispatch.',
    showPricesOnCourierReceipt: false,
  },
  taxSettings: {
    countryRates: [
      { countryCode: 'AE', taxClass: 'standard', taxRate: 5, taxLabel: 'VAT', isInclusive: false },
      { countryCode: 'KE', taxClass: 'standard', taxRate: 16, taxLabel: 'VAT', isInclusive: false },
      { countryCode: 'DE', taxClass: 'standard', taxRate: 19, taxLabel: 'VAT', isInclusive: false },
      { countryCode: 'US', taxClass: 'standard', taxRate: 0, taxLabel: 'Tax', isInclusive: false },
    ],
  },
  shippingRates: {
    countryRates: [
      { countryCode: 'AE', flatRate: 25, freeOver: 500, estimatedDays: '2-5 business days' },
      { countryCode: 'KE', baseRate: 35, perKgRate: 3, freeOver: 1000, estimatedDays: '5-10 business days' },
      { countryCode: 'DE', flatRate: 15, freeOver: 250, estimatedDays: '3-7 business days' },
      { countryCode: 'US', baseRate: 45, perKgRate: 4, estimatedDays: '5-14 business days' },
    ],
  },
  localization: {
    autoDetectCountry: true,
    defaultRegion: 'ae',
    supportedLanguages: [
      { code: 'en', label: 'English' },
      { code: 'ar', label: 'Arabic' },
      { code: 'fr', label: 'French' },
      { code: 'de', label: 'German' },
    ],
  },
  currencyDisplay: {
    enabled: false,
    baseCurrency: 'USD',
    marginPct: 2.5,
    showBothCurrencies: false,
  },
};

export default function AdminSettings() {
  const [form, setForm] = useState<AdminSettings>(defaults);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    api.get<Record<string, unknown>>('/admin/settings').then((response) => {
      const value = response.data as Partial<AdminSettings>;
      setForm({
        announcementBar: { ...defaults.announcementBar, ...(value.announcementBar ?? {}) },
        contact: { ...defaults.contact, ...(value.contact ?? {}) },
        trustBadges: value.trustBadges ?? defaults.trustBadges,
        footer: { ...defaults.footer, ...(value.footer ?? {}) },
        offerPopup: { ...defaults.offerPopup, ...(value.offerPopup ?? {}) },
        quoteAutomation: { ...defaults.quoteAutomation, ...(value.quoteAutomation ?? {}) },
        orderDocuments: { ...defaults.orderDocuments, ...(value.orderDocuments ?? {}) },
        taxSettings: { ...defaults.taxSettings, ...(value.taxSettings ?? {}) },
        shippingRates: { ...defaults.shippingRates, ...(value.shippingRates ?? {}) },
        localization: { ...defaults.localization, ...(value.localization ?? {}) },
        currencyDisplay: { ...defaults.currencyDisplay, ...((value.currencyDisplay as Partial<CurrencyDisplayForm>) ?? {}) },
      });
    }).catch(() => undefined);
  }, []);

  async function save() {
    setBusy(true);
    try {
      await Promise.all([
        api.put('/admin/settings/announcementBar', { value: form.announcementBar }),
        api.put('/admin/settings/contact', { value: form.contact }),
        api.put('/admin/settings/trustBadges', { value: form.trustBadges }),
        api.put('/admin/settings/footer', { value: form.footer }),
        api.put('/admin/settings/offerPopup', { value: form.offerPopup }),
        api.put('/admin/settings/quoteAutomation', { value: form.quoteAutomation }),
        api.put('/admin/settings/orderDocuments', { value: form.orderDocuments }),
        api.put('/admin/settings/taxSettings', { value: form.taxSettings }),
        api.put('/admin/settings/shippingRates', { value: form.shippingRates }),
        api.put('/admin/settings/localization', { value: form.localization }),
        api.put('/admin/settings/currencyDisplay', { value: form.currencyDisplay }),
      ]);
      setMessage('Site settings saved and available to the storefront.');
    } catch (error) {
      setMessage((error as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="max-w-5xl">
      <header className="mb-6 flex justify-between items-end gap-3">
        <div>
          <div className="section-eyebrow">CMS</div>
          <h1 className="mt-1 text-3xl font-extrabold">Site Settings</h1>
          <p className="text-sm text-brand-gray">Storefront content and automatic quotation delivery controls.</p>
        </div>
        <button className="btn-primary" disabled={busy} onClick={() => void save()}>{busy ? 'Saving...' : 'Save settings'}</button>
      </header>
      {message && <div className="card p-3 mb-4 text-sm">{message}</div>}

      <div className="grid lg:grid-cols-2 gap-4">
        <section className="card p-6 space-y-3">
          <h2 className="font-extrabold">Announcement bar</h2>
          <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.announcementBar.enabled} onChange={(event) => setForm({ ...form, announcementBar: { ...form.announcementBar, enabled: event.target.checked } })} /> Visible on storefront</label>
          <label className="block text-xs font-bold uppercase text-brand-gray">Messages, one per line</label>
          <textarea className="input min-h-[140px]" value={form.announcementBar.items.join('\n')} onChange={(event) => setForm({ ...form, announcementBar: { ...form.announcementBar, items: event.target.value.split('\n').filter(Boolean) } })} />
        </section>

        <section className="card p-6 space-y-3">
          <h2 className="font-extrabold">Contact</h2>
          {(['phone', 'whatsapp', 'email', 'salesEmail', 'headquarters'] as const).map((key) => (
            <label key={key} className="block">
              <span className="text-xs font-bold uppercase text-brand-gray">{key}</span>
              <input className="input mt-1" value={form.contact[key]} onChange={(event) => setForm({ ...form, contact: { ...form.contact, [key]: event.target.value } })} />
            </label>
          ))}
        </section>

        <section className="card p-6 space-y-3">
          <h2 className="font-extrabold">Trust badges</h2>
          {form.trustBadges.map((badge, index) => (
            <div key={index} className="grid grid-cols-[1fr_1fr_auto] gap-2">
              <input className="input" value={badge.label} placeholder="Label" onChange={(event) => {
                const next = [...form.trustBadges];
                next[index] = { ...badge, label: event.target.value };
                setForm({ ...form, trustBadges: next });
              }} />
              <input className="input" value={badge.image ?? ''} placeholder="/img/icons/..." onChange={(event) => {
                const next = [...form.trustBadges];
                next[index] = { ...badge, image: event.target.value };
                setForm({ ...form, trustBadges: next });
              }} />
              <button className="btn-ghost" onClick={() => setForm({ ...form, trustBadges: form.trustBadges.filter((_, i) => i !== index) })}>Remove</button>
            </div>
          ))}
          <button className="btn-outline btn-sm" onClick={() => setForm({ ...form, trustBadges: [...form.trustBadges, { label: '' }] })}>+ Badge</button>
        </section>

        <section className="card p-6 space-y-3">
          <h2 className="font-extrabold">Footer</h2>
          <label className="block text-xs font-bold uppercase text-brand-gray">Description</label>
          <textarea className="input min-h-[80px]" value={form.footer.description} onChange={(event) => setForm({ ...form, footer: { ...form.footer, description: event.target.value } })} />
          <label className="block text-xs font-bold uppercase text-brand-gray">Certifications, comma-separated</label>
          <input className="input" value={form.footer.certifications.join(', ')} onChange={(event) => setForm({ ...form, footer: { ...form.footer, certifications: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) } })} />
          {['linkedin', 'instagram', 'youtube', 'whatsapp'].map((network) => (
            <input key={network} className="input" placeholder={`${network} URL`} value={form.footer.social[network] ?? ''} onChange={(event) => setForm({ ...form, footer: { ...form.footer, social: { ...form.footer.social, [network]: event.target.value } } })} />
          ))}
        </section>

        <section className="card p-6 space-y-3 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Offer popup</h2>
            <p className="mt-1 text-xs text-brand-gray">Optional storefront modal for promotions, RFQ nudges or campaigns.</p>
          </div>
          <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.offerPopup.enabled} onChange={(event) => setForm({ ...form, offerPopup: { ...form.offerPopup, enabled: event.target.checked } })} /> Enable popup</label>
          <div className="grid gap-3 md:grid-cols-2">
            <label className="block"><span className="text-xs font-bold uppercase text-brand-gray">Title</span><input className="input mt-1" value={form.offerPopup.title} onChange={(event) => setForm({ ...form, offerPopup: { ...form.offerPopup, title: event.target.value } })} /></label>
            <label className="block"><span className="text-xs font-bold uppercase text-brand-gray">CTA label</span><input className="input mt-1" value={form.offerPopup.ctaLabel} onChange={(event) => setForm({ ...form, offerPopup: { ...form.offerPopup, ctaLabel: event.target.value } })} /></label>
            <label className="block"><span className="text-xs font-bold uppercase text-brand-gray">CTA URL</span><input className="input mt-1" value={form.offerPopup.ctaUrl} onChange={(event) => setForm({ ...form, offerPopup: { ...form.offerPopup, ctaUrl: event.target.value } })} /></label>
            <label className="block"><span className="text-xs font-bold uppercase text-brand-gray">Frequency hours</span><input type="number" min={1} max={720} className="input mt-1" value={form.offerPopup.frequencyHours} onChange={(event) => setForm({ ...form, offerPopup: { ...form.offerPopup, frequencyHours: Number(event.target.value) } })} /></label>
            <label className="block md:col-span-2"><span className="text-xs font-bold uppercase text-brand-gray">Body</span><textarea className="input mt-1 min-h-[80px]" value={form.offerPopup.body} onChange={(event) => setForm({ ...form, offerPopup: { ...form.offerPopup, body: event.target.value } })} /></label>
          </div>
        </section>

        <section className="card p-6 space-y-3 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Automatic quotations</h2>
            <p className="mt-1 text-xs text-brand-gray">Automatically price catalog RFQs and email the formal PDF below the approval threshold.</p>
          </div>
          <div className="flex flex-wrap gap-6">
            <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.quoteAutomation.enabled} onChange={(event) => setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, enabled: event.target.checked } })} /> Enable automatic pricing</label>
            <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.quoteAutomation.autoSend} onChange={(event) => setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, autoSend: event.target.checked } })} /> Send qualifying quotations automatically</label>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <label className="block">
              <span className="text-xs font-bold uppercase text-brand-gray">Auto-send maximum value</span>
              <input type="number" min={0} className="input mt-1" value={form.quoteAutomation.maxAutoValue} onChange={(event) => setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, maxAutoValue: Number(event.target.value) } })} />
            </label>
            <label className="block">
              <span className="text-xs font-bold uppercase text-brand-gray">Validity days</span>
              <input type="number" min={1} max={90} className="input mt-1" value={form.quoteAutomation.validityDays} onChange={(event) => setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, validityDays: Number(event.target.value) } })} />
            </label>
          </div>
          <div className="space-y-2">
            <div className="text-xs font-bold uppercase text-brand-gray">Quantity discount tiers</div>
            {form.quoteAutomation.discountTiers.map((tier, index) => (
              <div key={index} className="grid grid-cols-[1fr_1fr_auto] gap-2">
                <input type="number" min={1} className="input" aria-label="Minimum quantity" value={tier.minQuantity} onChange={(event) => {
                  const next = [...form.quoteAutomation.discountTiers];
                  next[index] = { ...tier, minQuantity: Number(event.target.value) };
                  setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, discountTiers: next } });
                }} />
                <input type="number" min={0} max={50} className="input" aria-label="Discount percent" value={tier.discountPercent} onChange={(event) => {
                  const next = [...form.quoteAutomation.discountTiers];
                  next[index] = { ...tier, discountPercent: Number(event.target.value) };
                  setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, discountTiers: next } });
                }} />
                <button className="btn-ghost" onClick={() => setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, discountTiers: form.quoteAutomation.discountTiers.filter((_, i) => i !== index) } })}>Remove</button>
              </div>
            ))}
            <button className="btn-outline btn-sm" onClick={() => setForm({ ...form, quoteAutomation: { ...form.quoteAutomation, discountTiers: [...form.quoteAutomation.discountTiers, { minQuantity: 1, discountPercent: 0 }] } })}>+ Tier</button>
          </div>
        </section>

        <section className="card p-6 space-y-3 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Order documents</h2>
            <p className="mt-1 text-xs text-brand-gray">Controls automatic PDF invoice and courier receipt generation for customer orders.</p>
          </div>
          <div className="flex flex-wrap gap-6">
            <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.orderDocuments.autoGenerateInvoiceOnOrder} onChange={(event) => setForm({ ...form, orderDocuments: { ...form.orderDocuments, autoGenerateInvoiceOnOrder: event.target.checked } })} /> Auto-generate invoice on order</label>
            <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.orderDocuments.autoGenerateCourierReceiptOnShipment} onChange={(event) => setForm({ ...form, orderDocuments: { ...form.orderDocuments, autoGenerateCourierReceiptOnShipment: event.target.checked } })} /> Auto-generate courier receipt on shipment</label>
            <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.orderDocuments.showPricesOnCourierReceipt} onChange={(event) => setForm({ ...form, orderDocuments: { ...form.orderDocuments, showPricesOnCourierReceipt: event.target.checked } })} /> Show prices on courier receipt</label>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <label className="block">
              <span className="text-xs font-bold uppercase text-brand-gray">Default courier</span>
              <input className="input mt-1" value={form.orderDocuments.defaultCourier} onChange={(event) => setForm({ ...form, orderDocuments: { ...form.orderDocuments, defaultCourier: event.target.value } })} />
            </label>
            <label className="block md:col-span-2">
              <span className="text-xs font-bold uppercase text-brand-gray">Courier receipt footer</span>
              <textarea className="input mt-1 min-h-[80px]" value={form.orderDocuments.receiptFooter} onChange={(event) => setForm({ ...form, orderDocuments: { ...form.orderDocuments, receiptFooter: event.target.value } })} />
            </label>
          </div>
        </section>

        <section className="card p-6 space-y-3 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Tax settings</h2>
            <p className="mt-1 text-xs text-brand-gray">Used by cart, checkout, quotations and invoices when calculating regional tax.</p>
          </div>
          <div className="space-y-2">
            {form.taxSettings.countryRates.map((row, index) => (
              <div key={index} className="grid gap-2 md:grid-cols-[90px_1fr_120px_120px_120px_auto]">
                <input className="input" value={row.countryCode} placeholder="AE" onChange={(event) => {
                  const next = [...form.taxSettings.countryRates];
                  next[index] = { ...row, countryCode: event.target.value.toUpperCase() };
                  setForm({ ...form, taxSettings: { countryRates: next } });
                }} />
                <input className="input" value={row.taxClass} placeholder="standard" onChange={(event) => {
                  const next = [...form.taxSettings.countryRates];
                  next[index] = { ...row, taxClass: event.target.value };
                  setForm({ ...form, taxSettings: { countryRates: next } });
                }} />
                <input type="number" min={0} max={100} className="input" value={row.taxRate} onChange={(event) => {
                  const next = [...form.taxSettings.countryRates];
                  next[index] = { ...row, taxRate: Number(event.target.value) };
                  setForm({ ...form, taxSettings: { countryRates: next } });
                }} />
                <input className="input" value={row.taxLabel} placeholder="VAT" onChange={(event) => {
                  const next = [...form.taxSettings.countryRates];
                  next[index] = { ...row, taxLabel: event.target.value };
                  setForm({ ...form, taxSettings: { countryRates: next } });
                }} />
                <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={row.isInclusive} onChange={(event) => {
                  const next = [...form.taxSettings.countryRates];
                  next[index] = { ...row, isInclusive: event.target.checked };
                  setForm({ ...form, taxSettings: { countryRates: next } });
                }} /> Inclusive</label>
                <button className="btn-ghost" onClick={() => setForm({ ...form, taxSettings: { countryRates: form.taxSettings.countryRates.filter((_, i) => i !== index) } })}>Remove</button>
              </div>
            ))}
          </div>
          <button className="btn-outline btn-sm" onClick={() => setForm({ ...form, taxSettings: { countryRates: [...form.taxSettings.countryRates, { countryCode: 'AE', taxClass: 'standard', taxRate: 0, taxLabel: 'VAT', isInclusive: false }] } })}>+ Tax country</button>
        </section>

        <section className="card p-6 space-y-3 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Shipping price settings</h2>
            <p className="mt-1 text-xs text-brand-gray">Flat rate wins when filled. Otherwise checkout uses base rate + product weight x per-kg rate. Free-over can make shipping zero.</p>
          </div>
          <div className="space-y-2">
            {form.shippingRates.countryRates.map((row, index) => (
              <div key={index} className="grid gap-2 md:grid-cols-[80px_110px_110px_110px_110px_1fr_auto]">
                <input className="input" value={row.countryCode} placeholder="AE" onChange={(event) => {
                  const next = [...form.shippingRates.countryRates];
                  next[index] = { ...row, countryCode: event.target.value.toUpperCase() };
                  setForm({ ...form, shippingRates: { countryRates: next } });
                }} />
                <NumberInput value={row.flatRate} placeholder="Flat" onChange={(value) => {
                  const next = [...form.shippingRates.countryRates];
                  next[index] = { ...row, flatRate: value };
                  setForm({ ...form, shippingRates: { countryRates: next } });
                }} />
                <NumberInput value={row.freeOver} placeholder="Free over" onChange={(value) => {
                  const next = [...form.shippingRates.countryRates];
                  next[index] = { ...row, freeOver: value };
                  setForm({ ...form, shippingRates: { countryRates: next } });
                }} />
                <NumberInput value={row.baseRate} placeholder="Base" onChange={(value) => {
                  const next = [...form.shippingRates.countryRates];
                  next[index] = { ...row, baseRate: value };
                  setForm({ ...form, shippingRates: { countryRates: next } });
                }} />
                <NumberInput value={row.perKgRate} placeholder="Per kg" onChange={(value) => {
                  const next = [...form.shippingRates.countryRates];
                  next[index] = { ...row, perKgRate: value };
                  setForm({ ...form, shippingRates: { countryRates: next } });
                }} />
                <input className="input" value={row.estimatedDays ?? ''} placeholder="2-5 business days" onChange={(event) => {
                  const next = [...form.shippingRates.countryRates];
                  next[index] = { ...row, estimatedDays: event.target.value };
                  setForm({ ...form, shippingRates: { countryRates: next } });
                }} />
                <button className="btn-ghost" onClick={() => setForm({ ...form, shippingRates: { countryRates: form.shippingRates.countryRates.filter((_, i) => i !== index) } })}>Remove</button>
              </div>
            ))}
          </div>
          <button className="btn-outline btn-sm" onClick={() => setForm({ ...form, shippingRates: { countryRates: [...form.shippingRates.countryRates, { countryCode: 'AE', flatRate: 0, estimatedDays: '5-14 business days' }] } })}>+ Shipping country</button>
        </section>

        <section className="card p-6 space-y-3 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Localization</h2>
            <p className="mt-1 text-xs text-brand-gray">Controls root country auto-detection and the storefront language selector. Translation content can be added later per CMS field.</p>
          </div>
          <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.localization.autoDetectCountry} onChange={(event) => setForm({ ...form, localization: { ...form.localization, autoDetectCountry: event.target.checked } })} /> Auto-detect country from IP headers on root URL</label>
          <label className="block">
            <span className="text-xs font-bold uppercase text-brand-gray">Default region</span>
            <input className="input mt-1" value={form.localization.defaultRegion} onChange={(event) => setForm({ ...form, localization: { ...form.localization, defaultRegion: event.target.value } })} />
          </label>
          <label className="block">
            <span className="text-xs font-bold uppercase text-brand-gray">Languages, one per line as code:label</span>
            <textarea className="input mt-1 min-h-[90px]" value={form.localization.supportedLanguages.map((language) => `${language.code}:${language.label}`).join('\n')} onChange={(event) => setForm({
              ...form,
              localization: {
                ...form.localization,
                supportedLanguages: event.target.value.split('\n').map((line) => {
                  const [code, ...label] = line.split(':');
                  return { code: code.trim(), label: (label.join(':') || code).trim() };
                }).filter((language) => language.code && language.label),
              },
            })} />
          </label>
        </section>

        <section className="card p-6 space-y-4 lg:col-span-2">
          <div>
            <h2 className="font-extrabold">Currency display &amp; live exchange rates</h2>
            <p className="mt-1 text-xs text-brand-gray">
              When enabled, the storefront converts prices from your base currency (e.g. USD) to each
              customer's local currency using real-time exchange rates from open.er-api.com, updated hourly.
              Your margin is added on top of the mid-market rate so you always earn the spread.
            </p>
          </div>

          <div className="flex flex-wrap gap-6">
            <label className="flex items-center gap-2 text-sm font-semibold">
              <input type="checkbox" checked={form.currencyDisplay.enabled} onChange={(event) => setForm({ ...form, currencyDisplay: { ...form.currencyDisplay, enabled: event.target.checked } })} />
              Enable real-time currency conversion on storefront
            </label>
            <label className="flex items-center gap-2 text-sm font-semibold">
              <input type="checkbox" checked={form.currencyDisplay.showBothCurrencies} onChange={(event) => setForm({ ...form, currencyDisplay: { ...form.currencyDisplay, showBothCurrencies: event.target.checked } })} />
              Show both local and base currency price (e.g. "AED 367 (USD 100)")
            </label>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <label className="block">
              <span className="text-xs font-bold uppercase text-brand-gray">Base currency (prices are stored in this currency)</span>
              <select className="input mt-1" value={form.currencyDisplay.baseCurrency} onChange={(event) => setForm({ ...form, currencyDisplay: { ...form.currencyDisplay, baseCurrency: event.target.value } })}>
                <option value="USD">USD — US Dollar</option>
                <option value="AED">AED — UAE Dirham</option>
                <option value="EUR">EUR — Euro</option>
                <option value="GBP">GBP — British Pound</option>
                <option value="INR">INR — Indian Rupee</option>
              </select>
            </label>
            <label className="block">
              <span className="text-xs font-bold uppercase text-brand-gray">Your margin on top of live rate (%)</span>
              <input
                type="number"
                min={0}
                max={20}
                step={0.1}
                className="input mt-1"
                value={form.currencyDisplay.marginPct}
                onChange={(event) => setForm({ ...form, currencyDisplay: { ...form.currencyDisplay, marginPct: Number(event.target.value) } })}
              />
              <span className="mt-1 block text-xs text-brand-gray">
                e.g. 2.5% → a $100 product shows as AED 379 instead of AED 367 (rate × 1.025)
              </span>
            </label>
          </div>

          <LiveRatesPreview enabled={form.currencyDisplay.enabled} />
        </section>
      </div>
    </div>
  );
}

function LiveRatesPreview({ enabled }: { enabled: boolean }) {
  const [rates, setRates] = useState<{ rates: Record<string, number>; fetchedAt: string; marginPct: number } | null>(null);
  const [loading, setLoading] = useState(false);

  function fetchPreview() {
    setLoading(true);
    api.get<typeof rates>('/exchange-rates')
      .then((r) => setRates(r.data))
      .catch(() => undefined)
      .finally(() => setLoading(false));
  }

  const PREVIEW_CURRENCIES = ['AED', 'KES', 'EUR', 'GBP', 'INR', 'PKR', 'SAR', 'QAR'];

  return (
    <div>
      <div className="flex items-center gap-3">
        <button type="button" className="btn-outline btn-sm" onClick={fetchPreview} disabled={loading}>
          {loading ? 'Fetching...' : 'Preview live rates'}
        </button>
        {rates && <span className="text-xs text-brand-gray">Updated {new Date(rates.fetchedAt).toLocaleTimeString()} · {rates.marginPct}% margin applied</span>}
      </div>
      {rates && (
        <div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-2">
          {PREVIEW_CURRENCIES.map((code) => {
            const rate = rates.rates[code];
            if (!rate) return null;
            return (
              <div key={code} className="rounded-lg border border-gray-100 px-3 py-2 text-sm">
                <span className="font-bold text-brand-blue">{code}</span>
                <span className="ml-2 font-mono">{rate.toFixed(4)}</span>
                <span className="block text-[11px] text-brand-gray">per 1 USD</span>
              </div>
            );
          })}
        </div>
      )}
      {!enabled && <p className="mt-2 text-xs text-brand-gray">Enable the toggle above and save to activate real-time prices on the storefront.</p>}
    </div>
  );
}

function NumberInput({ value, placeholder, onChange }: { value?: number; placeholder: string; onChange: (value: number | undefined) => void }) {
  return <input type="number" min={0} className="input" value={value ?? ''} placeholder={placeholder} onChange={(event) => onChange(event.target.value === '' ? undefined : Number(event.target.value))} />;
}
